export const commonResumeWords = [
  'liderança',
  'organização',
  'proativo',
  'responsável',
  'colaborativo',
  'eficiência',
  'resultados',
  'comunicação',
  'desenvolvimento',
  'gestão',
  'metas',
  'equipe',
  'estratégia',
  'negociação',
  'planejamento',
  'análise',
  'criatividade',
  'experiência',
  'aprendizado',
  'resiliência',
  'foco',
  'adaptabilidade',
  'iniciativa',
  'dedicação',
  'resolução',
  'conhecimento',
  'entusiasmo',
  'tecnologia',
  'qualidade',
  'inovação',
  'comprometimento',
  'pontualidade',
  'ética',
  'produtividade',
  'agilidade',
  'empatia',
  'persuasão',
  'gestão de projetos',
  'liderar',
  'implementação',
  'otimização',
  'colaboração',
  'resolutividade',
  'autonomia',
  'aprendizagem',
  'certificação',
  'competência',
  'desempenho',
  'proatividade',
  'gestão de tempo',
  'solução',
  'tecnológico',
  'motivação',
  'flexibilidade',
  'coordenação',
  'supervisão',
  'programação',
  'análise de dados',
  'melhoria contínua',
  'relacionamento',
  'profissionalismo',
  'visão estratégica',
  'integridade',
  'persistência',
  'gestão de conflitos',
  'trabalho em equipe',
  'inovador',
  'capacitação',
  'eficácia',
  'respeito',
  'python',
  'javascript',
  'java',
  'sql',
  'node.js',
  'react',
  'angular',
  'vue.js',
  'typescript',
  'html',
  'css',
  'devops',
  'agile',
  'scrum',
  'kanban',
  'cloud computing',
  'aws',
  'azure',
  'google cloud',
  'docker',
  'kubernetes',
  'git',
  'github',
  'gitlab',
  'bitbucket',
  'ci/cd',
  'machine learning',
  'inteligência artificial',
  'big data',
  'data science',
  'business intelligence',
  'power bi',
  'tableau',
  'excel',
  'banco de dados',
  'api',
  'rest',
  'graphql',
  'segurança da informação',
  'cibersegurança',
  'testes automatizados',
  'qualidade de software',
  'arquitetura de software',
  'frontend',
  'backend',
  'full stack',
  'mobile',
  'android',
  'ios',
  'flutter',
  'react native',
  'ui/ux',
  'prototipagem',
  'figma',
  'adobe xd',
  'gestão de riscos',
  'lean',
  'six sigma',
  'erp',
  'sap',
  'oracle',
  'crm',
  'salesforce',
  'marketing digital',
  'seo',
  'sem',
  'redes sociais',
  'gestão de mudanças',
  'mentoria',
  'treinamento',
  'onboarding',
  'kpi',
  'dashboard',
  'automação',
  'robótica',
  'blockchain',
  'internet das coisas',
  'iot',
  'realidade aumentada',
  'realidade virtual',
  'gestão de processos',
  'customer success',
  'experiência do cliente',
  'atendimento ao cliente',
  'vendas',
  'negócios',
  'empreendedorismo',
  'gestão financeira',
  'orçamento',
  'produtos',
  'serviços',
  'analista',
  'gerente',
  'desenvolvedor',
  'engenheiro',
  'coordenador',
  'supervisor',
  'consultor',
  'especialista',
  'diretor',
  'estagiário',
  'assistente',
  'técnico',
  'administrador',
  'arquiteto',
  'designer',
  'product owner',
  'scrum master',
  'analista de negócios',
  'gestor',
  'líder',
  'programador',
  'analista de sistemas',
  'analista de dados',
  'cientista de dados',
  'engenheiro de dados',
  'especialista em segurança',
  'analista de marketing',
  'gestor de projetos',
  'consultor de vendas',
  'representante comercial',
  'executivo de contas',
  'recrutador',
  'analista de rh',
  'gestor de rh',
  'treinador',
  'facilitador',
  'auditor',
  'contador',
  'analista financeiro',
  'engenheiro de software',
  'desenvolvedor frontend',
  'desenvolvedor backend',
  'desenvolvedor full stack',
  'administrador de banco de dados',
  'especialista em cloud',
  'profissional de marketing',
  'gestor de produtos',
  'analista de qualidade',
  'engenheiro de produção',
  'técnico de suporte',
  "linkedin",
  "github",
  "instagram",
  "facebook",
  "twitter",
  "youtube",
  "linkedin",
  "twitter",
];